downloads:
- M:\Downloaded
- D:\Downloaded\Netflix
- D:\Downloaded\Apple TV
- D:\Downloaded\Disney+
last_move_target: M:\Movies
local_shares: {}
locations:
- M:\Movies
- n:\
- M:\Movies\Itunes
naming:
  delete_images: true
  file_equals_folder: true
  movie_file: '{title} ({year})'
  movie_folder: '{title} ({year})'
  rename_files: true
  resolve_nfos: true
  sanitize_names: true
  series_folder: '{title} ({year})'
server_mode: false
transcode:
  audio_languages:
  - eng
  audio_prefer: first
  audio_reject_words:
  - description
  - descriptive
  - described
  - commentary
  - sdh
  - visual
  encoder: hevc_amf
  ffmpeg_path: d:\tools\ffmpeg\bin\ffmpeg.exe
  ffprobe_path: d:\tools\ffmpeg\bin\ffprobe.exe
  output_root: d:\transcoded
  qp: 22
